= Pulp SWADE
Andy Hall <achall@gmail.com>
v1.0, 2020-02-15
:toc: left
:experimental:
:sectlinks:
:sectanchors:

****
This is an attempt to take the setting rules from several older Savage Worlds products and adapt them to Savage Worlds Adventure Edition games.

This document also references:

* Triple Ace Games' _Daring Tales of Adventure Pulp Rules_
* Adamant Entertainment's _Thrilling Tales of Adventure_
****

== Heroes in the "Golden Age" of Pulp



=== Acts and scenes

Typically, an adventure is divided into 3 acts; each consists of 3 or 4 scenes.

=== Acting bad is bad

The protagonists are heroes. Play them that way. If a protagonist commits an evil, villainous, or morally ambiguous act, they lose a benny. This benny loss reduces the protagonist's benny maximum until the start of the next session. For example, if the hero typically starts a session with 3 bennies, her benny limit would then be reduced to 2 for the duration of the session.
[TIP]
Gamemaster, warn the player about this rules and the consequences of the action before the player's hero commits the unheroic deed.

=== Bennies

Before the start of every combat, each hero gets a benny, provided that the benny does not exceed the character's amount of bennies at the session's start. A typical wild card hero has 3 bennies at session start, unless the hero as edges or hindrances that affect starting bennies.

==== Stunts
// From Adamant Entertainment's "Thrilling Tales of Adventure"

A stunt action is any action that is performed in a flashier than normal way.
Any hero who attempts a stunt action deserves a benny.

In game terms, a stunt is an action where the player purposefully makes the action more difficult for the hero. A stunt action always requires a trait roll, at a minimum -2 penalty. The GM is the final arbiter of the roll penalty of a particular stunt action.

.Conventional action
****
Getting on board an airship before it lifts off from the platform is an action
****

.Stunt action
****
Leaping from the sidecar of a speeding motorcycle onto an airship at the last second as it lifts off from the platform.
****

=== Cinematic death
In a pulp game, death is not gory and messy.

=== Contacts

Once per adventure, one of the players can invent a Contact, who is a slightly helpful non-player character. A player may invent a Contact for his hero once per rank.
A contact typically serves to provide gear,  information, or clues and leads when parties are struggling. The GM gets the final decision on what the Contact provides the heroes.

////
 === Henchmen

An NPC henchman has three wounds like a wild card but, in all other respects, they are extras (that is, no wild die, no bennies for an non-player character wild card).

////

=== Heroic combat

////
==== Damage by Extras

The damage rolls of Extras do not ace.
////

==== Soaking

When a hero soaks all of the damage from an attack, she gets her benny back.

==== Nonlethal

All damage taken by heroes is treated as nonlethal. A hero can only die if a villain performs a Finishing Move (SWADE p 101).

////
==== Fast healing

Heroes recover 1 wound at the start of an "Act". See <<_acts_and_scenes>>.
////

==== Injuries are temporary

Heroes do not suffer a permanent injury. When the wounds from the injury heals, the hero no longer suffers the effect of the injury.

=== Never ending ammo

At the end of the scene, heroes recover all spent ammunition.
// At the end of the scene, heroes recover all spent Power Points.

=== Police interference

The cops never turn up until after the action.

=== Pulp fisted

Heroes never suffer the Unarmed Defender penalty (SWADE p 109).

=== Recurring villains

All of the villains that the GM wants to return in a sequel are treated as having the Harder to Kill edge (SWADE p 42) but with a 100% chance of survival.

The GM can also spend a benny to guarantee a villain's escape. The escaping villain ignores all die rolls and action limits. He cannot perform actions that he is normally incapable of taking and he cannot attack. Heroes who are on hold cannot interrupt the escape.

[WARNING]
The "Recurring villains" setting rules are be a bit _too_ much. Do not get too committed to the survival of a villain. Make some allowance for the heroes to kill them off.

=== Surrender

When the heroes surrender at a dramatically fitting place in the story and go along with the demands of the antagonists, each heroes takes a benny.


== Races
Heroes are humans.

== Skills

=== Changed skills

* Electronics is reskinned as Gadgetry

=== Removed skills

* Hacking
* Focus, applies to the Arcane Background (Gifted)
* Faith, applies to the Arcane Background (Miracles)
* Language (see the Multiple Languages setting rules in SWADE p 149)
* Psionics, applies to the Arcane Background (Psionics)
* Spellcasting, applies to the Arcane Background (Magic)

== Edges

=== Changed edges

New Powers (SWADE p 47)::
//An arcane character may learn two new powers by choosing this Edge (which may be taken multiple times). He may choose from any powers of his Rank or lower normally available to his particular Arcane Background.
//A character can add a new Trapping on a power she already has instead of gaining a new one. She might add an ice Trapping to her existing fire bolt, for example, so she could switch between ice and fire Trappings freely.
The weird scientist may learn one new power by choosing this Edge (which may be taken multiple times). She may choose from any powers of her Rank or lower that are normally available to Arcane Background (Weird Science).
This character can also add a new Trapping on a power she already has instead of gaining a new one. For example, she might add an electrical Trapping to her existing freeze bolt, for example, so she could switch between shock and cold Trappings.


=== Removed edges

* Arcane Resistance (SWADE p 37) and Improved Arcane Resistance
* Giant Killer (SWADE p 42)
* Linguist (as per the Multiple Languages setting rules in SWADE p 149)
* See <<_arcane_backgrounds>> for other unavailable edges

=== Arcane backgrounds

Only the Weird Science arcane background is allowed for heroes.
Heroes cannot use the other arcane backgrounds. Edges that are specifically applicable to unavailable arcane backgrounds are also not available to heroes.

The unavailable edges are:

** Extra Effort (SWADE p 46)
** Holy/Unholy Warrior (SWADE p 46)
** Mentalist (SWADE p 46)
** Wizard (SWADE p 47)


////
The following arcane backgrounds are allowed for villains:

* Weird science
* Psionics
* Magic
////

== Hindrances

Cocky (minor)::
The character is a braggart and will typically spend the /first round of any combat announcing how great he is, or what he's going to do to any and all opponents.
****
This is the minor version of the Overconfident (major) hindrance (SWADE p 26). This could easily be considered as a trapping of the hindrance Quirk (minor).
****


== Powers

Fly (SWADE p 162)::
For heroes with the Arcane Background (Weird Science) edge, Fly is available at Novice rank.

== Setting Rules

* Creative Combat (SWADE p 137)
* Fast Healing (SWADE p 139)
* Multiple Languages (SWADE p 149)
* Wound Cap (SWADE p 141)
* Dumb Luck (SWADE p 138)
* Fanatics (SWADE p 138)
* Heroes Never Die (SWADE p 140)
// * High Adventure (SWADE p 140)
// Born a Hero (SWADE p 136)








////
=== Success with a cost

If you roll a 1 on your skill die but your wild die is successful, the result is still considered a success, but there is a negative effect or compromise (e.g., your weapon becomes entangled in an enemy's armor). The player can describe what the negative effect looks like.
////
