
:dtoa: Daring Tales of Adventure 

== About

This document is an effort to take the setting rules from several older Savage Worlds products and adapt them to _Savage Worlds Adventure Edition_ (SWADE) games. 
The goal is to make the scenarios of the  _Daring Tales of Adventure_ series more usable for SWADE game masters and players.

The _{dtoa}_ series of Savage Worlds scenarios are available on https://www.drivethrurpg.com/[DriveThruRPG] and at better gaming stores everywhere.
The series was published by http://www.tripleacegames.com/category/daring-tales-of-adventure/[Triple Ace Games] and Paul "Wiggy" Wade-Williams is the mastermind behind the series.


=== Playing Pulp Adventures

The players, the GM included, are trying to mimic pulp action films.
The heroes are _virtually_ immortal; they perform daring deeds and take extreme risks. 


=== Players and {dtoa}

The adventures in the series are geared toward pre-generated four heroes:

Brent Hardcastle:: The brash pilot and "leading man" (http://tripleacegames.com/Downloads/DaringTales/DToA_Brent%20Hardcastle.pdf[Official PDF])
Lady Amelia "Duchess" Valentine:: The aristocratic action heroine (http://tripleacegames.com/Downloads/DaringTales/DToA_Lady%20Amelia%20Duchess%20Valentine.pdf[Official PDF])
Jimmy Patterson:: The resourceful punk kid (http://tripleacegames.com/Downloads/DaringTales/DToA_Jimmy%20Patterson.pdf[Official PDF])
Doctor Nathaniel "Doc" Davenport:: The eccentric inventor (http://tripleacegames.com/Downloads/DaringTales/DToA_Doctor%20Nathaniel%20Doc%20Davenport.pdf[Official PDF])

These characters were created for an earlier version of Savage Worlds.
Each hero's advances are mapped out in the characters sheet. 
The scenarios in the {dtoa} series are tied to the number of experience level of the pre-generated heroes.  

IMPORTANT: Players do not have to use the pre-generated heroes.
Make up your own pulp action heroes and make them your own.

A GM can work around the heroes not using the pre-generated heroes.
When running these games, it is helpful if the heroes who are engaged in the adventure have most of the abilities of the pre-generated heroes.
For example, there are many scenarios where the Piloting or Driving skills gets special focus. 

The {dtoa} scenarios do not lend themselves to a drop-in and drop-out type of game unless, on each drop-in, the heroes play the pre-generated heroes.

If you have more than four players, you may have more flexibility with respect to ability coverage, but there are other challenges.
More players can slow down game play and you want to keep the pace of game-play fairly quick. 

If you have fewer than four players, you may want to "beef up" the heroes (e.g., with a few more _advances_) to fill in for any missing abilities or competencies.



=== Expectations for the Pulp Action Campaign

.Player Attendance
****
Players must commit to attend each session of a scenario.
Don't ask for a longer commitment.
A {dtoa} scenario typically runs for 3-4 sessions of 2.5-3 hours.
****


// We are using the Savage Worlds Adventure Edition (SWADE) rules.

// * Determine setting rules up front and keep houseruling to a minimum
// * Unless we state otherwise, heroes are awarded an average of 1 advance every 2 sessions
// * If you miss a session, you get no credit for an advance and your character will operate as an allied extra

//<!-- * After a few sessions, I expect players to have a licensed copy of the SWDEE (an affordable $10 USD) -->

// == When we're playing Savage Worlds

* We want to follow the "Fast, Furious, and Fun" ethos.
Do your part to keep the pace of the game relatively brisk.
// * We're playing on a virtual tabletop (likely Roll20); I am not planning to over-invest in visual aids unless they are especially evocative.
// * Learn the Roll20 technology for Savage Worlds but you do not need to know Roll20 when you first join
** Learn the Savage Worlds rules; if you're new to Savage Worlds rules, you can download the most recent https://www.peginc.com/tag/test-drive-rules/[Savage Worlds Test Drive]
** If you have any rules for your character's schticks (e.g., arcane powers or gambling), learn them or have the rules handy
* You'll get bennies for trying to do cool things, making the game fun and interesting, playing according to the tone, and playing hindrances
* Bring your imagination and a willingness to narrate and add to the story footnote:[https://thealexandrian.net/wordpress/44891/roleplaying-games/gm-dont-list-11-description-on-demand and https://gamingandbs.com/descriptions-on-demand-in-rpgs-gbs308/]
* Be engaged during the game session and do your best to pay attention
* Share the stage so your fellow players can shine
// * Plan to make the game entertaining, interesting, and challenging
* If you cannot attend the game at the specified time, give reasonable advanced notice
* Give the GM feedback on what is working well, what you want to see more of, and what could use some work
* Prepare to engage in an adult conversation if we ever need to course correct
// * Be open to trying new tools for communication
* Stay classy

////
== Goals

As a GM and player, I have these goals:

* To build some memorable gaming stories together
* Make the game fun, or at least engaging, for all involved
* To become a better GM; to develop as player
* To encourage and help other players and GMs
////
