= Classic Pulp Adventure Heroes
:docdatetime:
:toc: left
:toclevels: 4
:experimental:
:sectlinks:
:sectanchors:


****
This is an effort to take the setting rules from several older Savage Worlds products and adapt them to _Savage Worlds Adventure Edition_ (SWADE) games. 
The goal is to make the scenarios of the  _Daring Tales of Adventure_ series more usable for SWADE game masters and players.
****

== References

In addition _Savage Worlds Adventure Edition_ (2018), this document references the following books:

* _Daring Tales of Adventure: Pulp Rules_ (2008, Paul "Wiggy" Wade-Williams, Triple Ace Games)
* _Daring Tales of Adventure: Rocket Rangers_ (2010, Paul "Wiggy" Wade-Williams, Triple Ace Games)
* _Savage Worlds Pulp GM's Toolkit_ (2006, Paul "Wiggy" Wade-Williams, Pinnacle Entertainment)
* _Thrilling Tales of Adventure_ (2009, Gareth-Michael Skarka et al., Adamant Entertainment)
* _Realms of Cthulhu_ (2009, Sean Preston, Reality Blurs)
* _The Eye of Kilquato: Savage Worlds Adventure Edition_ (2019, Shane Hensley, Pinnacle Entertainment)
* _Savage Daddy's One Shot Wonders_ (2018, Atomic Ninja Studios)



include::DTOA_chargen.adoc[]

include::DTOA_setting_rules.adoc[]