== Creating Heroes

=== Motivations

.Suggested motivations:
* Money
* Higher purpose (e.g., preserve, protect)
* Adventure and thrills
* Reputation, glory, and fame
* Professional rivalry
* Redemption


=== Races

Heroes are humans.

=== Skills

Pulp heroes are more capable than most.
At character creation, they start with 15 skill points.

////
==== New skills

#The Tradecraft skill may not make the final cut of these rules. The skill is really meant for heroes who are spies. If the character is a spy, then much of what we call tradecraft is just common knowledge.#

Tradecraft (Smarts)::
This skill focuses on the application of procedures and protocols, such as dead drops, brief encounters, pickups, load and unload signals, danger and safe signals, and surveillance and counter-surveillance. 
The tradecraft skill also covers knowledge of espionage agencies as well as aiding in field requisitions and governs exactly what you can requisition.
////


==== Changed Skills

// * Electronics is reskinned as Gadgetry
* Hacking is reskinned as Cryptopgraphy + 
It assumes some knowledge of codes and code breaking (e.g., Morse code) and mathematics



==== Removed Skills

// * Hacking
* Focus, applies to the Arcane Background (Gifted)
* Faith, applies to the Arcane Background (Miracles)
* Language (see the Multiple Languages setting rules in SWADE p 140)
* Psionics, applies to the Arcane Background (Psionics)
* Spellcasting, applies to the Arcane Background (Magic)

=== Edges

==== Changed Edges

New Powers (SWADE p 47)::
//An arcane character may learn two new powers by choosing this Edge (which may be taken multiple times). He may choose from any powers of his Rank or lower normally available to his particular Arcane Background.
//A character can add a new Trapping on a power she already has instead of gaining a new one. She might add an ice Trapping to her existing fire bolt, for example, so she could switch between ice and fire Trappings freely.
The weird scientist adds *one* new power by choosing this Edge (which may be taken multiple times) _and_ one new power trapping.
For the new power, the hero may choose from any powers of her Rank or lower that are normally available to Arcane Background (Weird Science).
For the new trapping, the hero adds an effect to an existing power.
For example, the player might add an electrical Trapping to her hero's existing freeze bolt; she can then switch between shock and cold Trappings.


==== Removed Edges

* Linguist (as per the Multiple Languages setting rules in SWADE p 140)
* See <<#arcane_bg>> for other unavailable edges
// * Arcane Resistance (SWADE p 37) and Improved Arcane Resistance
// * Giant Killer (SWADE p 42)


[[arcane_bg]]
==== Arcane Backgrounds

Only the Weird Science arcane background is available for heroes.
Edges that are associated with unavailable arcane backgrounds are not available to heroes.

.Why No Psionics?
****
I do not think heroes control the minds of others, wipe others' memories, and project mental blasts.
Let's focus on fists, bullets, and car chases and leave the superhuman and supernatural stuff to the big villains.
****

.Unavailable edges are:
** Extra Effort (SWADE p 46)
** Holy/Unholy Warrior (SWADE p 46)
** Mentalist (SWADE p 46)
** Wizard (SWADE p 47)

.Men of mystery and street-level superheroes
****
If we were to build heroes such as the _The Shadow_ and _Doc Savage_, we'd likely be using the Arcane Backgrounds of Gifted or Psionics.
In this campaign, we are focusing on a low-powered, classic pulp adventure game _a la_ the Indiana Jones movies or the Mummy series.
****


////
The following arcane backgrounds are allowed for villains:

* Weird science
* Psionics
* Magic
////

=== Hindrances

Cocky (minor)::
The character is a braggart and will typically spend the first round of any combat announcing how great he is, or what he's going to do to any and all opponents.
Cocky is a minor version of the Overconfident (major) hindrance (SWADE p 26).
// This could easily be considered as a trapping of the hindrance Quirk (minor).


=== Powers

Fly (SWADE p 162)::
For heroes with the Arcane Background (Weird Science) edge, Fly is available at Novice rank.



=== Archetypes

The character archetypes described below are suggestions and do not specify dice values.

.Improved edges
****
For simplicity's sake, I do not list the _improved_ version of an edge. For example, when I list the Luck edge, I do not list the Great Luck edge. Take the improved version of the edge later, when the character advances.
****

==== Actor

Suggested Skills::
Athletics, Fighting, Intimidation, Performance, Persuasion, Riding, Taunt
Suggested Edges::
Attractive, Charismatic, Connections, Elan, Fame, Rich, Work the Room
Suggested Hindrances::
Arrogant, Big Mouth, Habit, Think Skinned, Stubborn

==== Archaeologist

Suggested Skills::
Academics, Athletics, Notice, Repair, Research, Stealth, Survival
Suggested Edges::
Investigator, Scholar, Danger Sense, Dodge, Luck
Suggested Hindrances::
Code of Honor, Heroic, Bad Luck, Curious, Greedy, Phobia

==== Big Game Hunter

Suggested Skills::
Athletics, Fighting, Notice, Riding, Shooting, Stealth, Survival
Suggested Edges::
Alertness, Danger Sense, Dead Shot, Giant Killer, Marksman, No Mercy, Steady Hands, Trademark Weapon, Woodsman.
Suggested Hindrances::
Arrogant, Bloodthirsty, Greedy

==== Commander

Suggested Skills::
Battle, Fighting, Intimidation,  Notice, Persuasion,  Shooting
Suggested Edges::
Command, Natural Leader
Suggested Hindrances::
Loyal, Code of Honor

==== Dilettante

Suggested Skills::
Athletics, Driving, Gambling, Performance, Persuasion, Riding, Shooting, Taunt
Suggested Edges::
Aristocrat, Fame, Rich
Suggested Hindrances::
All Thumbs, Arrogant, Clueless, Code of Honor, Impulsive, Obligation, Overconfident, Secret, Shamed, Think Skinned, Vengeful

==== Explorer

Suggested Skills::
Academics, Athletics, Healing, Notice, Research, Riding, Science, Survival
Suggested Edges::
Brave, Scholar, Strong Willed, Woodsman
Suggested Hindrances::
Bad Luck, Code of Honor, Curious, Driven, Stubborn
////
==== Fortune hunter

Suggested Skills::
Research, Academics, Thievery, Notice, Survival
Suggested Edges::
Investigator, Scholar
Suggested Hindrances::
Bad Luck, Curious, Greedy, Phobia
////
==== G-Man

Suggested Skills::
Common Knowledge, Driving, Fighting, Intimidation, Notice, Research, Persuasion, Shooting
Suggested Edges::
Alertness, Combat Reflexes, Command, Connections, Dodge, Investigator, Strong Willed
Suggested Hindrances::
Code of Honor, Loyal, Mean, Obligation, Overconfident


==== Jungle Man

Suggested Skills::
Athletics, Fighting, Healing, Notice, Survival, Stealth
Suggested Edges::
Acrobat, Alertness, Beast Bond, Beast Master, Brawny, Danger Sense, Fleet-Footed, Free Runner, Giant Killer, Iron Jaw, Woodsman
Suggested Hindrances::
All Thumbs, Clueless, Curious, Heroic, Illiterate, Outsider



==== Mad Scientist

Suggested Skills::
Athletics,  _Gadgetry_, Research, Repair, Science, Shooting, Weird Science
Suggested Edges::
Arcane Background (Weird Science), Gadgeteer, McGyver, Mr. Fix It, Rich
Suggested Hindrances::
Curious, Delusional, Doubting Thomas, Outsider, Overconfident

////
==== Man of Mystery

Suggested Skills::
text
Suggested Edges::
text
Suggested Hindrances::
text
////

==== Martial Artist

Suggested Skills::
Athletics, Fighting, Intimidation, Stealth
Suggested Edges::
Acrobat, Ambidextrous, Block, Chi, First Strike, Frenzy, Martial Artist
Suggested Hindrances::
Driven, Heroic, Loyal, Outsider, Pacifist, Vow

////
==== Mesmerist

Suggested Skills::
Intimidation, Notice, Performance, Persuasion, Psionics.
Suggested Edges::
Arcane Background (Psionics), Arcane Resistance (Psionics), Danger Sense, Mentalist, Soul Drain, Strong Willed
Suggested Hindrances::
Cautious, Pacifist
////

==== Pilot

Suggested Skills::
Piloting, Repair, Shooting
Suggested Edges::
Ace, Dead Shot, Level-Headed, Quick, Steady Hands,
Suggested Hindrances::
Arrogant, Code of Honor, Enemy, Outsider, Overconfident


==== Private Detective

Suggested Skills::
Research, Stealth, Notice, Persuasion, Performance, Taunt
Suggested Edges::
Alertness, Connections, Investigator, Streetwise
Suggested Hindrances::
Code of Honor, Curious

==== Prizefighter

Suggested Skills::
Athletics, Fighting, Intimidation
Suggested Edges::
Ambidextrous, Block, Brawler, Brawny, Bruiser, Brute, Combat Reflexes, Counterattack, Fame, First Strike, Frenzy, Iron Jaw, Martial Artist, Quick, Strong Willed, Sweep, Two Fisted
Suggested Hindrances::
Arrogant, Driven, Heroic, Illiterate, Loyal, Menacing, Overconfident, Ruthless, Ugly


==== Punk Kid

Suggested Skills::
Athletics, Notice, Persuasion, Repair, Stealth, Taunt
Suggested Edges::
Alertness, Acrobat, Dodge, Extraction, Fleet Footed, Humiliate, Luck, Provoke, Quick, Retort, Scavenger, Strong Willed,
Suggested Hindrances::
Big Mouth, Curious, Loyal, Young


==== Reformed Criminal

Suggested Skills::
Athletics, Fighting, Gambling, Intimidation, Notice, Persuasion, Shooting, Stealth, Taunt, Thievery
Suggested Edges::
Acrobat, Assassin, Calculating, Connections, Dodge, Free Runner, Level Headed, Menacing, Rock and Roll, Streetwise, Thief
Suggested Hindrances::
Code of Honor, Enemy, Greedy, Habit, Heroic, Mean, Ruthless, Secret, Shamed, Suspicious, Ugly, Vow, Wanted

==== Reporter

Suggested Skills::
Academics, Athletics, Notice, Persuasion, Research, Stealth, Taunt, Thievery
Suggested Edges::
Alertness, Attractive, Calculating, Connections, Investigator, Luck, Streetwise, Strong Willed
Suggested Hindrances::
Curious, Doubting Thomas, Driven, Habit, Suspicious

==== Rocketeer

Suggested Skills::
Athletics, Fighting, Intimidation, Piloting, Shooting, Stealth
Suggested Edges::
Ace, Combat Reflexes, Dodge, Level Headed, Rock 'n' Roll, Steady Hands
Suggested Hindrances::
Code of Honor, Heroic, Loyal, Overconfident

==== Soldier of Fortune

Suggested Skills::
Athletics, Battle, Fighting, Intimidation, Notice, Riding, Shooting, Stealth
Suggested Edges::
Enlisted;;
Combat Reflexes, Dodge, Marksman, Rock and Roll, Soldier, Steady Hands
Officer;;
Command, Command Presence, Hold the Line, Inspire, Natural Leader, Tactician
Suggested Hindrances::
Greedy, Loyal

==== Star Athlete

Suggested Skills::
Athletics, Fighting, Intimidation, Performance, Riding, Taunt
Suggested Edges::
Acrobat, Attractive, Brawny, Brute, Elan, Fame, Fleet Footed, Free Runner, Level Headed, Quick
Bolster, Common Bond, Provoke, Reliable, Strong Willed
Suggested Hindrances::
Arrogant, Driven, Heroic, Ruthless, Thin Skinned, Young

////
==== Archetype name 1

Suggested Skills::
text
Suggested Edges::
text
Suggested Hindrances::
text
////
