
= Setting Rules for Pulp Adventure Heroes
:docdatetime:
:toc: left
:toclevels: 4
:experimental:
:sectlinks:
:sectanchors:

// Classic Two-Fisted Pulp Adventures Using _Savage Worlds Adventure Edition_
****
This is an effort to take the setting rules from several older Savage Worlds products and adapt them to _Savage Worlds Adventure Edition_ (SWADE) games. 
// The goal is to make the scenarios of the  _Daring Tales of Adventure_ series more usable for SWADE game masters and players.
****
////
== Heroes in the "Golden Age" of Pulp

=== Acts and scenes

Typically, a "Daring Tales of Adventure" scenario was divided into 3 or 4 acts; each act usually consists of 3 or 4 scenes.
////
== Standard settings rules

Savage Worlds Adventure Edition has a number of setting rules that are perfect for running a two-fisted pulp game.

* Conviction (SWADE p 136)
// Initially, "Creative combat"  just seemed to slow combat and most results were _Shaken_. That was because I was running the rules wrong.
* Creative Combat (SWADE p 137)
* Dumb Luck (SWADE p 138)
* Fanatics (SWADE p 138)
* Fast Healing (SWADE p 139)
* Heroes Never Die (SWADE p 140)
* High Adventure (SWADE p 140)
* Multiple Languages (SWADE p 149)
* Wound Cap (SWADE p 141)
// Born a Hero (SWADE p 136)

////
.Why not use the Wound Cap setting rule?
****
I thought of adding the Wound Cap setting rule (SWADE p 141) but I figured that, with Fast Healing, Dumb Luck, Heroes Never Die,  <<#injuries_are_temporary>>, and  <<#nonlethal_damage_to_heroes>>, the heroes were wearing enough bubble wrap. There has to be _some_ danger.
****
////

== Special setting rules

The following rules and directions further tune the setting for a classic pulp action game.


////
=== Bennies

Before the start of every combat, each hero gets a benny, provided that the benny does not exceed the character's amount of bennies at the session's start. A typical wild card hero has 3 bennies at session start, unless the hero as edges or hindrances that affect starting bennies.
////

=== Be the Hero

The protagonists are heroes.
Play them that way.
If a protagonist commits an evil, villainous, or morally ambiguous act, they lose a benny.
This benny loss reduces the protagonist's benny maximum until the start of the next session.
For example, if the hero typically starts a session with 3 bennies, her benny limit would then be reduced to 2 for the duration of the session.

TIP: The GM should warn the player about this rule and the consequences of the action before the player's hero commits an ignoble deed.

////
==== Soaking

When a hero soaks all of the damage from an attack, she gets her benny back.
////

=== Stunts
// From Adamant Entertainment's "Thrilling Tales of Adventure"

A stunt action is any action that is performed in a flashier than normal way.
Any hero who attempts a stunt action deserves a benny.

In game terms, a stunt is an action where the player purposefully makes the action more difficult for the hero.
A stunt action always requires a trait roll, at a minimum -2 penalty.
The GM is the final arbiter of the roll penalty of a particular stunt action.

Conventional action::
Getting on board an airship before it lifts off from the platform is an action

Stunt action::
Leaping from the sidecar of a speeding motorcycle onto an airship at the last second as it lifts off from the platform.

=== Surrender

When the heroes surrender at a dramatically fitting place in the story and go along with the demands of the antagonists, each heroes takes a benny.

=== Pay It Forward
When a Wild Card gets more than one raise on any Trait roll (including Soak rolls), they receive a Benny as a way to pay their luck forward.

=== Cinematic Death
In a pulp game, death is not gory and messy.

////
==== Contacts

Once per adventure, one of the players can invent a Contact, who is a slightly helpful non-player character.
// A player may invent a Contact for his hero once per rank.
A contact typically serves to provide gear, information, or clues and leads when parties are struggling.
The GM gets the final decision on what the Contact provides the heroes.
////
////
 === Henchmen

An NPC henchman has three wounds like a wild card but, in all other respects, they are extras (that is, no wild die, no bennies for an non-player character wild card).

////

// === Heroic Combat

////
 ==== Damage by Extras

The damage rolls of Extras do not ace.
////

////
[[nonlethal_damage_to_heroes]]
=== Nonlethal Damage to Heroes

All damage taken by heroes is treated as nonlethal.
A hero can only die if a villain performs a Finishing Move (SWADE p 101).
////
////
==== Fast healing

Heroes recover 1 wound at the start of an "Act". See <<_acts_and_scenes>>.
////

////
[[injuries_are_temporary]]
=== Injuries are Temporary

Heroes do not suffer a permanent injury. When the wounds from the injury heals, the hero no longer suffers the effect of the injury.
////

=== Never-Ending Ammo

At the end of the scene, heroes recover all spent ammunition.
// At the end of the scene, heroes recover all spent Power Points.

////
=== Pulp Fisted

Heroes never suffer the Unarmed Defender penalty (SWADE p 109).
////

////
=== Recurring villains

All of the villains that the GM wants to return in a sequel are treated as having the Harder to Kill edge (SWADE p 42) but with a 100% chance of survival.

The GM can also spend a benny to guarantee a villain's escape. The escaping villain ignores all die rolls and action limits. He cannot perform actions that he is normally incapable of taking and he cannot attack. Heroes who are on hold cannot interrupt the escape.

[WARNING]
The "Recurring villains" setting rules are a bit _too_ much. Do not get too committed to the survival of a villain. Make some allowance for the heroes to kill them off.
////

=== Police Interference

The cops do not turn up on the scene until after the action has ended.








////
 === Success with a cost

If you roll a 1 on your skill die but your wild die is successful, the result is still considered a success, but there is a negative effect or compromise (e.g., your weapon becomes entangled in an enemy's armor). The player can describe what the negative effect looks like.
////
