= Savage Pendragon
:toc: left
:toclevel: 6







== Ethnicity and ancestry

== Edges


=== Changes to existing edges

Aristocrat::
#What has changed?#


=== New edges

Intrigue::
Like Streetwise, but +2 networking rolls around court.

== Skills

=== New skills

Animal handling::
#More info#



=== Removed skills

* Hacking
* Electronics

=== Changes to skill


Common Knowledge::
Common knowledge covers such subjects and uses such as

* Heraldry
* Steward
* Court

== Virtues, vices, and passions



== Jousting rules

****
These rules leverage the rules on jousting in the scenario "Death at the Joust", which are part of the _Daring Tales of Chivalry_ setting rules (Triple Ace Games).
****

////
As well as being a public display of wealth by the
hosting noble, a tournament is a chance for knights to
knock each other off their horses, gain fame and wealth
(and sometimes ladies), and, in times of peace, to maintain
their skill at arms. These displays of horsemanship
are known as jousts, and are governed by strict rules.
Knights are valuable assets, and although death is always
a risk, the rules exist to ensure most suffer only broken
bones and wounded pride. Jousts can also be used by
knights to settle disputes, though battering each other
into submission was usually the standard way of sorting
out problems.
////

=== Basic tournament jousting
Tourney jousting focuses on unhorsing your opponent.
Jousting lances are designed to break on impact and be nonlethal. 
Accidents will happen, however.

Jousting lances cost £0.10 each. Buy more than one.

To run a joust combat, a hero must have a horse.
Armor is optional, but few knights joust without armor.
Most knights wear heavy armor to protect themselves.

==== The "standard elimination" joust

In this type of joust, the names of riders are randomly drawn by lot to face each other; the winner moves on to the next round.
If there are too few knights to form an equal number of pairs to a power of two, the contestant with the highest social rank or who are renowned tournament champions receive a free pass to the next round.

.How jousting match-ups are determined
====
In a joust with 18 riders, there are nine pairs.
However, 18 is not a power of two, but 16 is (2x2x2x2).
The two knights of greatest renown or status take a free pass.
The 16 knights are whittled down to eight, and then down to four.
When these four have jousted, the final pair each faces one of the knights who received a frees pass to determine who appears in the final match.
====

==== Rules of the joust

Who can joust?::
Only nobles or knights may joust.
Females are not knowingly permitted to joust.
Ownership::
A contestant must own his own horse and equipment.
Starting etiquette::
At the start of a match, the host's flag is raised over the center of the barrier.
Knights ride on the right-hand side of the barrier.
Squire's role::
If a knight falls, only the squire may help him.
When the lance is broken, only the squire may hand the lance to the knight.
Only the squire may talk to the knight when preparing the horse for the next charge.


==== Matches
Each match consists of three _runs_.
Between each run there is a 10-minute delay.
This allows time for armor dents to be straightened out, and a single Healing roll.

===== Scoring
A successful hit to the torso in which the lance shatters earns one point.
A head shot (–4 penalty) and a broken lance earns two points.
Unseating a rider, no matter where he is struck gives the attacker 3 points.

The match winner is the knight who scores the most points. 
If there is a tie, a knight who has unseated his opponent more times than he has been unseated is determined to be the winner.
If there is still a tie, the knight with the most head shots wins.
In the event they are still equal, both knights face an "overtime" final run.
A further tie results in both knights being eliminated from the competition.

At the end of a match, a knight who has unseated his opponent more times than he has been unseated may claim his rival’s horse as a prize.
It is traditional to allow the rival to buy back his mount at the full market price.

==== Initiative
In a joust, both knights strike within a fraction of a second.
Action cards are not used to determine who goes first, but Jokers carry their usual benefits.
Both participants roll to hit simultaneously.


==== Attacks

.Procedure
. Determine the horse
. Select a jousting maneuver
. Make the fighting rolls

===== Determine the type of horse

Two types of horses are permitted in jousts:

warm-blood chargers (standard riding horse)::
Grants the rider +2 damage.
cold-blood destriers (warhorse)::
Grants the rider +1 Fighting.

===== Jousting maneuvers

Although the attacks are simultaneous, a knight has a variety of maneuvers that he can employ.
Each player participant secretly selects a jousting maneuver from the options below.

On the physical tabletop, you can place a d6 face up to match the option number behind a cupped hand.
When both are ready, reveal the dice simultaneously.

On the VTT, an easy way to handle this is to message the GM with your jousting maneuver.

.Standard jousting maneuvers
====
Braced (1):: The knight braces himself for a hit, but in doing so loses accuracy for his own attack.
He gains +2 to Riding rolls to remain mounted, but suffers a –2 penalty on his attack.
Aggressive (2):: This is essentially a Wild Attack.
The knight has +2 to Fighting rolls and damage, but suffers a –2 penalty to his Parry.
Standard (3):: No modifiers apply.
Head Shot (4):: The knight is trying to earn more points.
His attack roll is made at –4, but he inflicts +4 damage (and thus also has a greater chance of unseating his opponent). If his opponent has his eyes fixed (see below), he also risks killing him.
Eyes Fixed (5):: Just before impact, knights tend to look away from their opponent.
This lessens the chance of a wooden splinter piercing the helmet’s visor and causing lethal injury.
A knight who keeps his eyes fixed on his target gains +1 to his Fighting roll, but if he takes a head shot the damage is considered lethal.
Deflective (6):: The knight turns his body at the last second, hoping his opponent’s lance will glance off his shoulder.
He has +1 Parry but –1 to Fighting.
====

===== Fighting roll
Both attackers then roll their Fighting or Riding die (plus Wild Die if applicable) as appropriate and apply all modifiers.


==== Damage

Damage for a jousting lance is `Str+d6`; there is no AP. 
Damage is treated as nonlethal but the dice can still Ace.
Results from the "Injury Table" still apply but they are only temporary until all of the wounds are healed.
Unless you take a Called Shot (i.e., the "Head Shot" maneuver), you automatically hit the knight’s torso.
If the victim is at least Shaken, the attacker’s lance shatters (a broken lance earns points).

See <<#_scoring>>.

Otherwise, the hit is considered a glancing blow and no points are tallied _unless the target falls from his horse_.

NOTE: In a joust, knights do not get the Charging bonus of +4 damage.

==== Falling from your horse
When a jouster is struck, he must make a Riding roll or fall from his mount.
// This replaces the usual rule that he must be Shaken or wounded first.
Falling from a horse causes 2d6 damage.
If both opponents fall in the same round, both may remount, and each scores 3 points.

===== Forfeiting the match
A knight may withdraw from a match at any time.
// Typically this is done when facing an important nobleman, as causing him injury, or killing him, limits one’s social aspirations.
// Some nobles disguise their identity under a pseudonym or lesser title in order they may joust and actually face opponents.
If a knight takes more than 10 minutes between runs is disqualified.
If a knight strikes a horse, whether by accident or not, he is disqualified.

////
==== CHALLENGES
Jousts also serve as a way of airing grievances, seeking satisfaction of honor, or even gaining a small favor.
A noble may challenge any other noble.
However, a social superior does not have to accept a challenge, and his reputation is not tarnished for refusing—one cannot expect the king to joust with a knight, for instance.
Likewise, asking for something the challenged knight cannot give (the throne of England, for example), results in the challenger becoming a laughing stock.
The challenger must publicly state the reason for the challenge.
Typical challenges are grudge matches, to win back a lost possession, or even the seemingly trivial request of a kiss from a noble’s daughter (or wife, if the hero has
the nerve to ask).
Challenges are not the same as duels in later periods—they are never fought to the death.
Instead, the challenged knight sets the terms. At minimum,
////


== Status

****
These rules are derived from the rules on status in the _Rippers Players' Guide_.
****

Status is of great importance.
A hero’s Status reflects not only his position in society, but also the esteem in which he is held, his ability to affect those around him, and his approximate wealth.

Your hero’s Status starts as 4 (gentry), but can be affected by Edges and Hindrances as well as by his or her actions during the course of the game.

Status is not a reflection of your hero’s standing amongst other knights.
That is shown by your character’s Rank (Novice, Seasoned, and so on).


=== Social order

Your character’s Status can be used to influence others.
Inferiors are not permitted to socialize with their betters.
There are, however, certain notable exceptions able to fraternize with nearly all ranks of society.

Status is crucial for determining how characters interact with people of different stations.
In general, the “inferior” classes are expected to show a proper modicum of respect to their “betters,” and the upper classes expected to adopt a protective, almost patriarchal
stance over the less fortunate.
The very concept of status is based on a responsibility to aid those who have aided you in the past.
A person’s status determines their influence and ability to call upon more powerful favors from those who owe them.
All too often, status is used as a means of intimidation by the upper classes, and an excuse for surliness by lower
classes.

Status is rated in six levels, as shown in the <<#status_table,Status table>>.

// Every member of a given status level receives the listed salary at the end of each month of game time.
// These amounts replace those listed for the Rich and Filthy Rich Edges in Savage Worlds.
Starting characters, assumed to be knights, begin as Gentry (status 4), barring Edges or a Hindrance that alters their Status.

Being Rich increases Status by +1 level, and Filthy Rich increases it by another +1.
Characters with the Aristocrat edge have their starting Status increased by +1 level.
The Poverty hindrance reduces Status by –1 level.

You cannot reduce a knight's status below 4 (Gentry) at character generation.

[[status_table]]
.Status table
A character may have the Rich edge (or Filthy Rich) and the Poverty hindrance.
This might reflect someone who has a wealth, but spends it wastefully (resulting in a lower Status level and reduced wealth).

[options="header",cols=","]
|===
| Status | Max. Favor Cost
| Underclass |  1
| Peasantry | 2
| Artisan/Merchant class  | 3
| Gentry | 4
| Lesser Nobility | 5
| Greater Nobility | 6
|===

// A character’s Status cannot drop lower than Underclass.


=== Status effects

People of different status levels do not interact as equals; the upper classes tend look down on the lower ones and the lower classes tend to resent and envy their “betters.”

Upper classes wield power over the lower ones.
When using the Intimidation skill, a character gains a +1 bonus for each Status level he is higher than his target, or suffers a –1 penalty for each Status level he is lower.

On the other side, higher classes are more easily incensed by the mocking of those beneath their station, while the lower classes are unimpressed by the ridicule of those who have such an easy life.
Characters gain +1 to Taunt rolls for each Status level they are lower than their target, or suffer a –1 penalty for each Status level they are higher than their target.

The downside of class separation is that no class talks freely or shares information with someone of another station.
Any attempt at Networking suffers a –1 penalty for each level of Status difference between the characters.


== Talking to nobles

Lesser knights and most people of similar or lesser standing do not have easy access to speak to nobles or members of the court.

Practically anyone can attempt to gain access to speak to a noble. 


=== Petitioning for an audience

See "GAINING AUDIENCES" in the scenario "Death at the Joust" for the initial rules on this. 
#These rules will be updated and simplified.# 

=== Appealing to a noble

#Use the SWADE Social Conflict rules.#



== Glory

****
These rules are derived from the rules on Glory in the _Hellfrost Player's Guide_ (Triple Ace Games).
****

Glory is a mark of a character’s reputation as a hero.
Only through heroic deeds can a character aspire to enter the annals of history books and oral history.

Glory is measured with Glory Points. +
Your hero’s Glory starts at zero but this value can be affected by his or her actions. +
The higher your knight's Glory, the more renowned he is and the more benefits he gains. +
Glory can go negative, but this grants no benefits.

=== Gaining glory

Glory is earned through heroic exploits.

After each adventure, and only when the heroes return to civilization, one member of the party may tell the tale of their heroic deeds and battles. +
The character makes a Performance roll, modified as described below.

The GM may add positive modifiers for truly heroic actions or based on the character’s weaknesses and how he overcame them.

Think of how the heroes’ true exploits (as opposed to any invented bits) sound as a tale that is told by a bard or poet.
This is important, because the listeners are effectively
granting the heroes Glory.
An extra +1 or +2 should be the maximum.
For instance, slaying a notorious giant is certainly worthy of praise, but that is already covered in the table. However, cleaving the head with a Called Shot as the killing blow is worth a small modifier, as it is the sort of detail found in epic poems.
Likewise, a Novice party who slay a bunch of greater foes in melee without any assistance should be rewarded with a greater chance of fame.

The GM may add penalties to reflect weaker opponents (such as ragged brigands) or favorable character circumstances.


.Deeds of glory
****
[options="header",cols="6,4"]
|===
| Reason | Modifier
2+a| **Storyteller**
| Is a trained poet | +1
| Has negative Glory | –2
2+a| **Highest Character Rank**
| Seasoned | –1
| Veteran | –2
| Heroic | –4
| Legendary | –6
2+a| **Highest Number of Foes**
| You outnumbered them | –1
| They outnumbered you more than 2 to 1 | +1
| They outnumbered you more than 4 to 1 | +2
| They outnumbered you more than 10 to 1 | +4
2+a| **Highest Foes’ Toughness**
| 4 or less | –1
| 5 to 6 | +0
| 7 to 10 | +1
| 11 to 15 | +2
| 16 to 20 | +4
| 21 or more | +6
2+a| **Wild Cards**
| Per Wild Card | +1
| Per named Wild Card | +2
| Per Wild Card killed in a single blow | +4
2+a| **Arcane Background**
| A foe had an AB with 5 or less powers | +1
| A foe had an AB with 6 to 10 powers | +2
| A foe had an AB with 11+ powers | +4
|===
****

Arcane Background:: Where multiple foes with an Arcane Background were defeated, only the highest bonus applies.
Character Rank:: The higher the heroes’ Rank, the more dangerous foes they must overcome before anyone is interested in their tales.
Foes’ Toughness:: Only the highest Toughness of defeated foes counts.
Named Wild Card:: Not every Wild Card should,
or indeed can, be named.
Named wild card foes are more memorable than unnamed foes. Number of Foes:: Only record the greatest number of foes slain in a single encounter.
Defeating three Pictish warriors in one combat and eight in another melee equates to only eight Pictish warriors.

.Party size and foes
****
The size of the party includes any allies on the heroes’ side - a party with 20 members must defeat a lot of foes at once to get noticed.
If the heroes forget to mention their helpers, any survivors will tell their own stories across the land.
****
Single Blow:: A Wild Card who is killed in a single blow must have been unwounded when the killing blow was delivered.
The foe must have been aware of the party and capable of retaliation.
Storyteller:: Although anyone can tell a story, the poets
are trained in using the right words and adjusting the rhythm to keep an audience enthralled.
They can turn even a mundane adventure into an epic struggle.

=== Glory awards

With a successful Performance roll, every hero involved in the action gains 1d6 Glory; a raise increases this to 2d6. +
Failure earns no bonus or penalty. +
A critical failure, however, causes the loss of 1d6 Glory.

Roll the dice for each individual member of the party earning or losing Glory.
Glory awards can be altered by the GM, but this should be done only for truly notable actions.
Modifiers normally apply to individual members of the party, not every member.

For example, the hero who delivered the Called Shot to the head, killing the infamous foe, should earn a +1 or +2 bonus for his notable deed.

Of course, if one hero played little part in the action, he should receive less Glory than those who were more actively involved.
Such a hero may roll his dice with a –3 penalty, for example, possibly earning a small penalty overall with an unlucky roll because of his inaction.



==== Fixed glory awards

Fixed Glory awards cover lesser deeds not played out (such as events during long periods of downtime), killing smaller number of foes during an adventure (they do slowly add up over time), or rewards for which there are many witnesses (battles or rescues).
These are in addition to any Glory gained above.
The GM can devise their own modifiers for things like concluding peace treaties making alliances that benefit a large population.
Although notable deeds, the rewards for these types of endeavor should not be overly high.

==== Achieving rank and gaining glory
Even without performing major heroic deeds, a knight can become famous through his collective lesser deeds.
Such rewards are typical of the examples above, especially the slaying of lesser foes.
These are wrapped into a single +5 Glory bonus gained when a hero achieves a new Rank
It is possible, though rare, for a hero to reach Legendary status with no additional Glory. In such a case, the knight has performed many deeds but none stand out as heroic.

==== Mass battle

War can grow and break reputations.
Use the table below whenever the characters are involved
in a fight using the Mass Battle rules.
Mass battles are relatively rare events.
All Glory modifiers are fixed.

.Glory for mass battles
****
[options="header",cols="6,4"]
|====
| Reason | Modifier
2+a| *Size*
| Smallest army had hundreds of troops | +1
| Smallest army had thousands of troops | +3
| Smallest army had more than 10,000 troops | +5
2+a| *Enemy*
| Saxon army | +/–1
2+a| *Victory*
| Enemy had less tokens or was equal | +1
| For each token the enemy had above yours | +2
2+a| *Defeat*
| Enemy had more tokens or was equal | –1
| For each token less your enemy had | –3
2+a| *Personal Heroics*
| Two raises on Heroes in Mass Battles roll | +1
2+a| *Commander*
| You commanded the army | x2
|====
****

Character Roll:: Scoring a double raise is more than
just a die result.
It represents a major event within a battle, such as vanquishing an enemy commander or cleaving through so many foes that a unit breaks.
The modifier only applies if the number of enemy tokens was less than or equal to your army’s tokens at the time (defeating an enemy commander when you have a +3 bonus is nowhere near as heroic as when you have a –3 penalty).
Commander:: A hero who commands an army gains greater Glory than his troops for victory, but also suffers more ignominy if he loses the field.
Take the final Glory modifier and double it to see what the knight earned.
Defeat:: Defeat is never easy to live with, but the ignominy is far worse if you outnumbered your foe.
For each token that you outnumbered your enemy by at the start of a battle, you suffer a –3 penalty.
Enemy Forces:: Certain races are more despised than
others.
To qualify for the bonus, the specific enemy must account for more than 75% of the enemy army’s troop strength.
Add the modifier if the heroes won, and subtract it if they lost.
Size:: Huge armies are rare and thus, while any battle earns Glory, the more participants there are, the greater the tale told.
Victory:: The greater the size of the enemy army, the more reward is earned.
For each token your enemy’s army was larger than yours when
the battle commenced, the hero earns a +2 Glory bonus.


==== Rescue

Even if the knight’s tale of his valorous deeds doesn’t earn them any immediate Glory, having prisoners recount the tale of their rescue quickly causes word to spread.

* Important NPCs must be famous, powerful, and _named_.
** A priest, minor noble, or similar noteworthy NPC is worth +1 Glory.
** Saving a count is worth +3.
** Rescuing a prince, king, or similar worthy gains the hero +5 Glory.

For groups of lesser NPCs, rescuing ten or so is worth +1 Glory, a few tens +2, and a hundred or more +3.
Saving a lone peasant is not enough to be retold by poets.

Rescue doesn’t have to mean entering a dungeon and breaking captives out.
If the rescue involves a Mass Battle rather than tabletop action, the party is deserving of the Mass Battle rewards as well.


.Villains and glory
****
Knights who perform heroic deeds earn bonuses through their elevated Glory. 
Those that perform dastardly deeds get little reward for being evil.
Of course, to earn Glory a knight has to take great risks and maintain a certain code of conduct; a villain doesn't have that limitation.
****

==== Benefits of glory

When a hero reaches a multiple of 20 Glory he must immediately pick one benefit from the list below, meeting any requirements.
Some knights may opt to acquire Followers or become leaders of men and build a personal army.
Other knights might use their fame to gain valuable connections or become better combatants.
Others still may prefer to rely on their reputation to ensure a friendly welcome in civilized lands.
Unless otherwise stated, benefits can be taken multiple times—the number in parentheses after the name indicates the maximum number of times the benefit may be taken.

Fill in the appropriate section of the character sheet.
// TK@fup Character sheet tracks glory and benefits

Should the Glory value drop below a multiple of 20, any benefits above the character’s current Glory level are temporarily lost (unless otherwise stated) until Glory is regained.
Dropping below 20 and then rising above it again does not grant the opportunity to take a new benefit—it simply allows the “lost” one to be used again.

===== COMBAT PROWESS (2)
Requirements:: 40+ Glory +
The knight may take a Combat Edge immediately.
He must meet all the requirements as normal.

===== CONNECTION (4)
Requirements:: 20+ Glory +
When a knight gains a Connection, he must pick a specific faction, as per the Edge of the same name.
The hero does not belong to the faction—he simply has friends among their number willing to assist him (though he may, at the GM’s discretion, be offered membership as well).
The Connection should be appropriate to the character’s background and his deeds.
Note that the hero still needs make a Networking check for this benefit to be of any use.

===== FAVORED (2)
Requirements:: 60+ Glory +
The knight can do things others can’t.
He gains an extra benny per session.

===== FOLLOWERS (10)
Requirements:: 40+ Glory +
The knight gains the Followers Edge regardless of his character Rank.
The GM and player work together to determine the nature of the Followers, based on the knight's deeds.
Followers are not automatically replaced when they die. Additional Followers may be gained at Legendary as normal through taking the Followers Edge with advances or by earning more Glory and taking this benefit.
+
Followers don’t automatically leave if a character’s Glory drops below the level he gained this benefit, but they begin to grumble, refuse orders, and eventually mutiny.
In game terms, the character’s Leadership Edges no longer work on them.
When his Glory rises above the threshold again, his Followers stop grumbling. +

NOTE: Having Extras accompany you on every mission means you have to slay more foes to earn Glory.

===== LEADER OF MEN (4)
Requirements:: 40+ Glory +
The character may take a Leadership Edge immediately.
He must meet all the requirements of the edge.

===== SIDEKICK (1)
Requirements:: 80+ Glory +
Regardless of his character Rank, the hero has attracted a Sidekick, as per the edge.
+
If the Sidekick dies, the character may take this benefit again when he earns more Glory.
A second Sidekick may be gained at Legendary as normal through taking the Sidekick edge with an advance.
+
Sidekicks remain with the hero when his Glory drops, but may grumble, not perform to the best of their abilities, or even refuse to follow orders.
When the Glory rises sufficiently high again, the Sidekick returns to his former loyal state.


==== LOSING GLORY
A knight must deliberately act in a less than heroic way to suffer a Glory penalty.
Since everyone makes mistakes, minor misdemeanors are ignored unless the knight makes them a bad habit of them.
Sample penalties are included below.

[options="header"]
|===
| Glory | Event
| Special | Slaying or defeating a good and just powerful knight or worthy
| –1 to –20 | Caught committing a crime
| –3 | Cowardice or leaving a comrade behind
// | –3 | Refusing Orders (the Hindrance)
| –10 | Breaking an oath
|===

Crime:: This is a catchall penalty covering anything
considered abhorrent to civilized society.
Oaths:: Knights who renege on sworn oaths are considered treacherous.
Slaying:: Killing a good, just, and powerful NPC, such as a king, causes a hero to suffer a drastic loss of Glory.
The knight's Glory is swapped from a positive to a negative immediately.
For instance, a knight with +50 Glory drops to –50 and becomes a very wanted man.

===== Negative glory
A knight with negative Glory does not earn rewards. He suffers drawbacks.

===== Wanted

When a hero reaches –20 Glory, he gains the Wanted (Minor) Hindrance. + 
At –40, this changes to the Major version. + 
Generally, the Minor Hindrance extends to a single realm, usually the one where the Glory penalty was incurred. + 
The Major version, on the other hand, covers pretty much all the civilized.
A hero who gains enough Glory to rise above the rating at which he gained this Hindrance, doesn’t lose the Hindrance. He may have performed some heroic deeds, but he is still a wanted man.

===== Enemy
At –10 Glory, the hero acquires the Enemy (Minor) Hindrance. + 
At –30 (or lower), the Enemy becomes a Major Hindrance. + 
The exact nature of the enemy depends on the villain’s deeds. 
It doesn’t matter if the hero’s Glory rises above the level at which he gained his foe, because his Enemy doesn’t give up his vendetta.
If the hero gains a Major Enemy while his Minor Enemy is still at large, the foe simply steps up his campaign against the character.
Otherwise, the hero gains a new enemy.



// ==== Inherited honor


// TK@FUP left off at Death and Honor

== Character death and replacement

When a character dies, his replacement begins with half of his advances (round down).
// However, high or low Glory at the time of the character’s death can alter this amount.
// When a character dies with below 99 Glory, the character has 50% Experience as standard.
// Between 100 and 199 Glory, the replacement has 75% Experience, and at 200 and over he retains the full Experience Points of his predecessor.

If the replacement is an heir of the now deceased character, then some of the glory is transferred to the new character.
The heir inherits 1/4 of his parent's Glory.  

== Squires

All knights begin with a squire, a loyal and trusted (or maybe not) companion to their master. 
Squires are typically male. 
Squires are there to support the knight and learn.

NOTE: A knight may have several squires at a time. 
The senior squire, the "squire of the body," commands the other squires, and has both the responsibilities and benefits of his post. 
He is usually the only squire to go with the knight into battle.

You create a squire as a regular character, except they are Extras, receive four attribute points, and eight skill points (plus the five default skills). 
No squire may ever have Fighting or Riding higher than d6. 
A capable squire typically has at least a Common Knowledge skill of d6.

A player should not create his own squire. 
Another player character builds the squire and plays him during the game. 
This allows for the knight to interact with his servant in play without the player talking to himself.

Whether or not the knight has any say in the character generation is up to the individual players.

A squire Advances like any other Extra (see Allies and Advancement in SWADE). 
A squire who dies is not automatically replaced - the character must use an advance to earn a new squire. 
Replaced squires begin with the same experience as their predecessor. 
Fortunately, most villains ignore squires who do not attack them. 
Unless a hero places his squire in direct danger, villains will always target a player character over the squire.

// The lackey’s basic salary (typically a small sum) is assumed covered by whatever income his master has. Any bonus rewards must come from the Musketeer’s pocket. 

Typically, a squire begins with the basic tools needed for his profession, a dagger, and appropriate clothing, though the lackey’s background may alter this.

A squire is usually age 15 at the start of his service, but as high as 20. 
When a squire reaches 21, he is usually knighted, whereupon you take a new squire of 15 years into service.
There are a few exceptions where a squire remains a squire after age 21.  

If you want to play a squire as a hero, go for it.


== Social duels
A social duel is an exchange of jests, barbed comments, overt or sly insults, witty slander, and backhanded compliments.
The social duel rules are intended for use in social occasions, such as at feasts and other occasions at court; they are not used in standard combat.
A social duel takes time and requires an audience to witness the exchange.

CAUTION: Be careful before you insult someone. 
Avoid insulting high status individuals unless you're reasonably certain you can win (or deal with the repercussions). See <<#results>>.

Social dueling works much like the Social Conflict rules (SWADE p 143) except that Taunt is used instead of Persuasion.

Another character can provide a Support roll but, if the duel is lost, that supporting character suffers the same penalties as the character who initiates the social duel.

NOTE: Not every NPC has Taunt. 
For the purpose of social dueling only, every NPC should be considered to have Taunt d4 unless he has a higher die listed—even the crudest peasant knows how to deliver a witty double entendre, throw an insult, or just deliver a defamatory statement in social situations.

[[results]]
=== Social dueling results
This replaces the Social Conflict Results table in the SWADE core rules.
Losers of a social duel suffer from a loss of reputation and self respect. #Not to glory?#
The penalties are removed at the rate of one point per week.
Word way spread quickly around the realm.
Any character with a damaged reputation will receive knowing smiles at best, and be mocked by all and sundry at worst.
Alternately, the loser can demand a duel. 
Should he win, the reputation is restored and all penalties are removed.
While the character is suffering a social penalty, he will not be the target of social duels — a damaged reputation cannot be further harmed until it is repaired.
He may, if he so chooses, instigate social duels, though.

[cols="20%,80%", options="header"]
|===
| Margin | Result
| Tie | 
There is no clear winner. 
Both parties have slandered each other, but the insults have not damaged their reputations. Neither feels the need to pursue the matter further, at least not until their next meeting.
| 1-2 | The loser’s honor and reputation are besmirched, but only temporarily. 
He suffers a –1 penalty to Intimidation, Persuasion, and Taunt rolls.
| 3-4 | A stinging remark has left a deep wound on the loser’s reputation. 
He suffers a –2 penalty to Intimidation, Persuasion, and Taunt roll.
| 5+ | The target’s honor is beyond tarnished! 
He suffers a –4 penalty to Intimidation, Persuasion, and Taunt rolls.
|===

How else might a character repair his reputation? Perform a deed of glory



== References

The xref:https://mostunreadblogever.blogspot.com/2018/04/savaging-pendragon.html[original proposal] is from Tommy Brownell.

// The scenario "Death at the Joust" contains the _Daring Tales of Adventure_ setting rules.

* _Hellfrost Player's Guide_ (2009, Paul "Wiggy" Wade-Williams, Triple Aces Games)
* _Death at the Joust_ (2008, Paul "Wiggy" Wade-Williams, Triple Aces Games) 
* _Rippers Player's Guide_ (2015, Simon Lucas et al., Pinnacle Entertainment Group)
* _King Arthur Pendragon_, (2010, Greg Stafford, Nocturnal Media)
* _All For One: Regime Diabolique_ (Second Edition (2019, Paul "Wiggy" Wade-Williams, Triple Aces Games)