== Savage Old School Fantasy

This campaign is an attempt to get close to emulating an "old school" megadungeon crawl experience using the Savage Worlds rules. 
The goal is to pay reproduce many of the best elements of the old school game play and, at the same, enjoy  Savage Worlds' fast-furious-fun play style.

We'll use Greg Gillespie's Barrowmaze (and the village of the Helix) as the mainstays of the setting.
Most sessions will run as a short foray into the Barrowmaze. Adventurers who attempt to sleep or make camp in the dungeon do not typically return to tell tales.   

Random encounters and wandering monsters will often be resolved using the quick combat rules.
As a Savage Worlds GM, I'll hand wave most resource management unless it makes the game story more interesting.   

As Savage Worlds does not require the killing of monsters or acquisition of treasure for character advancement, I plan to scale down the number of combats, eliminating ones that I see as less meaningful, and there will be somewhat less treasure.

There are traps but they tend to be less lethal to a Savage Worlds novice-level PC than they were to a first-level B/X magic-user.

You are welcome to hire and employ henchmen and hirelings (Savage Worlds allied extras). Players will control these extras in combat; make sure that your PCs treat the henchmen and hirelings fairly or they may turn (sneak away, run at a critical time, steal, or worse).

There is no need for a player to serve as  mapper or caller.

.Setting rules:
* Blood & Guts
// * Critical Failures
* Gritty Damage
// * Joker's Wild


.References:
* link:https://www.drivethrurpg.com/product/283156/GoldGlory-Seven-Deadly-Dungeons-Savage-Worlds-Adventure-Edition["Gold & Glory: Seven Deadly Dungeons (Savage Worlds Adventure Edition)]
* link:https://goodbadskinny.blogspot.com/2017/01/savage-warhammer.html[Savage Warhammer]
* link:https://www.drivethrurpg.com/product/273116/The-Tomb-of-Xenophon-MicroDungeon-Adventure-Savage-Worlds?filters=45582_0_1600_0_0[The Tomb of Xenophon: Micro-Dungeon Adventure (Savage Worlds)]
* link:https://www.drivethrurpg.com/product/265837/Tyrnador-JumpStart[Tyrnador JumpStart]
* link:https://www.drivethrurpg.com/product/275399/Icy-Belly-of-Fillion-Manor[Icy Belly of Fillion Manor]

.OSR Resources
* link:http://www.drivethrurpg.com/product/139762/Barrowmaze-Complete[Barrowmaze Complete]
* link:http://www.barrowmaze.com/meatshields[Meatshields! Hireling and Henchman Generator]